### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by ghost** [serializingme/hpqpswdd#1]
Sorry if I'm asking a stupid question here, but once I build it, how do I use it? Do I have to attach it to another program? Do I have to run it with certain arguments? And if so, what arguments?

Thanks in advance,
laffyfx

**Comment by serializingme** [comment]
Hi @laffyfx,

after compiling you can run it as `hpqpswdd.exe <name of the file with the HPQPswd encrypted password>`

Cheers,
Duarte

**Comment by ghost** [comment]
Thanks! I got it working!

**Comment by serializingme** [comment]
Forgot to close the issue 😃Good that it worked!
